import type {
  UserProfile,
  Skill,
  Project,
  Certificate,
  ActivityItem,
  Connection,
  AnalyticsData,
  AIInsight,
} from './types';

// Current User Profile
export const currentUser: UserProfile = {
  id: 'user-1',
  username: 'alex-johnson',
  displayName: 'Alex Johnson',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  coverImage: 'https://images.unsplash.com/photo-1555066931-4365d440a117?w=1200&h=300&fit=crop',
  bio: 'Full-stack developer, AI enthusiast, and open-source contributor. Building amazing web experiences and learning every day.',
  tagline: 'Transforming ideas into code',
  level: 12,
  xp: 4850,
  streak: 28,
  totalXp: 45600,
  joinDate: new Date('2023-06-15'),
  socialLinks: {
    github: 'https://github.com/alexjohnson',
    linkedin: 'https://linkedin.com/in/alexjohnson',
    twitter: 'https://twitter.com/alexjohnson',
    portfolio: 'https://alexjohnson.dev',
  },
  education: [
    {
      id: 'edu-1',
      institution: 'Stanford University',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      startDate: new Date('2016-09-01'),
      endDate: new Date('2020-05-31'),
      current: false,
    },
    {
      id: 'edu-2',
      institution: 'Stanford University',
      degree: 'Master of Science',
      field: 'Computer Science - AI',
      startDate: new Date('2020-09-01'),
      endDate: new Date('2022-05-31'),
      current: false,
    },
  ],
  experience: [
    {
      id: 'exp-1',
      company: 'Tech Innovations Inc',
      position: 'Senior Full-Stack Engineer',
      description: 'Led development of microservices architecture and mentored junior developers',
      startDate: new Date('2022-06-01'),
      current: true,
    },
    {
      id: 'exp-2',
      company: 'StartupXYZ',
      position: 'Full-Stack Engineer',
      description: 'Built and deployed React and Node.js applications',
      startDate: new Date('2021-01-01'),
      endDate: new Date('2022-05-31'),
      current: false,
    },
  ],
  privacy: {
    profileVisibility: 'public',
    activityVisibility: 'everyone',
    connectionRequests: 'everyone',
  },
  theme: 'dark',
};

// Skills
export const skills: Skill[] = [
  {
    id: 'skill-1',
    name: 'TypeScript',
    category: 'Languages',
    proficiency: 95,
    endorsements: 24,
    lastUsedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-2',
    name: 'React',
    category: 'Frontend',
    proficiency: 90,
    endorsements: 31,
    lastUsedDate: new Date(Date.now() - 0 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-3',
    name: 'Next.js',
    category: 'Frontend',
    proficiency: 88,
    endorsements: 18,
    lastUsedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-4',
    name: 'Node.js',
    category: 'Backend',
    proficiency: 85,
    endorsements: 22,
    lastUsedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-5',
    name: 'Python',
    category: 'Languages',
    proficiency: 80,
    endorsements: 15,
    lastUsedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-6',
    name: 'TensorFlow',
    category: 'AI/ML',
    proficiency: 75,
    endorsements: 12,
    lastUsedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-7',
    name: 'PostgreSQL',
    category: 'Data',
    proficiency: 82,
    endorsements: 14,
    lastUsedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-8',
    name: 'Docker',
    category: 'DevOps',
    proficiency: 78,
    endorsements: 11,
    lastUsedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
];

// Projects
export const projects: Project[] = [
  {
    id: 'proj-1',
    title: 'AI Content Generator',
    description: 'Intelligent content generation platform using GPT-4 API with React and Node.js',
    image: 'https://images.unsplash.com/photo-1633356713697-4be7b648105a?w=500&h=300&fit=crop',
    techStack: ['React', 'Node.js', 'TypeScript', 'GPT-4', 'Tailwind CSS'],
    category: 'AI',
    githubUrl: 'https://github.com/alexjohnson/ai-content-gen',
    liveUrl: 'https://ai-content-gen.demo.com',
    likes: 342,
    views: 2104,
    createdDate: new Date('2024-02-15'),
  },
  {
    id: 'proj-2',
    title: 'E-Commerce Platform',
    description: 'Full-stack e-commerce solution with Stripe integration and real-time inventory',
    image: 'https://images.unsplash.com/photo-1600693938461-6b13f2d1c8f9?w=500&h=300&fit=crop',
    techStack: ['Next.js', 'PostgreSQL', 'Stripe', 'Redis', 'Docker'],
    category: 'Web',
    githubUrl: 'https://github.com/alexjohnson/ecommerce-platform',
    liveUrl: 'https://ecommerce-demo.com',
    likes: 528,
    views: 3540,
    createdDate: new Date('2023-12-10'),
  },
  {
    id: 'proj-3',
    title: 'Analytics Dashboard',
    description: 'Real-time data visualization dashboard for business metrics and KPIs',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop',
    techStack: ['React', 'D3.js', 'TypeScript', 'Node.js', 'MongoDB'],
    category: 'Data',
    githubUrl: 'https://github.com/alexjohnson/analytics-dash',
    liveUrl: 'https://analytics-dashboard-demo.com',
    likes: 298,
    views: 1856,
    createdDate: new Date('2023-11-05'),
  },
  {
    id: 'proj-4',
    title: 'Mobile Weather App',
    description: 'Cross-platform weather application with real-time updates and location services',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&h=300&fit=crop',
    techStack: ['React Native', 'TypeScript', 'Firebase', 'Expo'],
    category: 'Mobile',
    githubUrl: 'https://github.com/alexjohnson/weather-app',
    likes: 156,
    views: 892,
    createdDate: new Date('2023-10-20'),
  },
];

// Certificates
export const certificates: Certificate[] = [
  {
    id: 'cert-1',
    name: 'Advanced React Patterns',
    issuer: 'Frontend Masters',
    issueDate: new Date('2024-01-15'),
    verificationId: 'FM-2024-001-ARP',
    url: 'https://frontendmasters.com/certificates/react-patterns',
  },
  {
    id: 'cert-2',
    name: 'Full-Stack JavaScript',
    issuer: 'The Complete JavaScript Course',
    issueDate: new Date('2023-11-20'),
    verificationId: 'UDEMY-2023-FSJ',
    url: 'https://udemy.com/certificates/full-stack-js',
  },
  {
    id: 'cert-3',
    name: 'Machine Learning Fundamentals',
    issuer: 'Coursera - Stanford University',
    issueDate: new Date('2023-09-10'),
    expirationDate: new Date('2025-09-10'),
    verificationId: 'COURSERA-ML-2023',
    url: 'https://coursera.org/certificates/ml-fundamentals',
  },
  {
    id: 'cert-4',
    name: 'AWS Cloud Practitioner',
    issuer: 'Amazon Web Services',
    issueDate: new Date('2023-08-05'),
    expirationDate: new Date('2025-08-05'),
    verificationId: 'AWS-CP-2023-08-05',
    url: 'https://aws.amazon.com/certificates',
  },
];

// Activity Feed
export const activityFeed: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'achievement',
    title: 'Reached Level 12!',
    description: 'You&apos;ve unlocked a new achievement level',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    metadata: { level: 12, reward: 500 },
  },
  {
    id: 'act-2',
    type: 'project_upload',
    title: 'Uploaded new project: AI Content Generator',
    description: 'Shared a new project to your portfolio',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    metadata: { projectId: 'proj-1' },
  },
  {
    id: 'act-3',
    type: 'skill_endorsed',
    title: 'Sarah Chen endorsed your React skill',
    description: 'Your React endorsements: 31',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    metadata: { skill: 'React', endorser: 'Sarah Chen' },
  },
  {
    id: 'act-4',
    type: 'course_completion',
    title: 'Completed: Advanced React Patterns',
    description: 'You earned 250 XP and a certificate',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    metadata: { xp: 250, certificateId: 'cert-1' },
  },
  {
    id: 'act-5',
    type: 'connection',
    title: 'Connected with Michael Park',
    description: 'You now have a mutual connection',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    metadata: { connectionId: 'conn-2' },
  },
  {
    id: 'act-6',
    type: 'badge_unlock',
    title: 'Earned "Code Master" Badge',
    description: 'You&apos;ve completed 50 coding challenges',
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    metadata: { badge: 'Code Master', progress: '50/50' },
  },
];

// Connections
export const connections: Connection[] = [
  {
    id: 'conn-1',
    name: 'Sarah Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    title: 'Full-Stack Engineer at Google',
    skills: ['React', 'Python', 'Machine Learning'],
    mutualCount: 8,
    isFollowing: true,
  },
  {
    id: 'conn-2',
    name: 'Michael Park',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    title: 'Product Manager at Meta',
    skills: ['Product Strategy', 'User Research', 'Data Analytics'],
    mutualCount: 5,
    isFollowing: true,
  },
  {
    id: 'conn-3',
    name: 'Emma Williams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    title: 'Designer at Figma',
    skills: ['UI Design', 'UX Research', 'Prototyping'],
    mutualCount: 12,
    isFollowing: true,
  },
  {
    id: 'conn-4',
    name: 'David Kumar',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    title: 'Data Scientist at OpenAI',
    skills: ['Machine Learning', 'TensorFlow', 'Data Science'],
    mutualCount: 3,
    isFollowing: false,
    isSuggested: true,
  },
  {
    id: 'conn-5',
    name: 'Lisa Rodriguez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    title: 'DevOps Engineer at Netflix',
    skills: ['Kubernetes', 'AWS', 'Docker'],
    mutualCount: 7,
    isFollowing: false,
    isSuggested: true,
  },
];

// Analytics Data
export const analyticsData: AnalyticsData = {
  xpHistory: [
    { date: 'Jan 1', xp: 1200 },
    { date: 'Jan 8', xp: 2100 },
    { date: 'Jan 15', xp: 3400 },
    { date: 'Jan 22', xp: 4200 },
    { date: 'Jan 29', xp: 5800 },
    { date: 'Feb 5', xp: 7100 },
    { date: 'Feb 12', xp: 8900 },
  ],
  studyTimeByDay: [
    { day: 'Monday', minutes: 120 },
    { day: 'Tuesday', minutes: 150 },
    { day: 'Wednesday', minutes: 90 },
    { day: 'Thursday', minutes: 180 },
    { day: 'Friday', minutes: 200 },
    { day: 'Saturday', minutes: 60 },
    { day: 'Sunday', minutes: 75 },
  ],
  skillProgress: [
    { skill: 'TypeScript', progress: 95 },
    { skill: 'React', progress: 90 },
    { skill: 'Next.js', progress: 88 },
    { skill: 'Node.js', progress: 85 },
    { skill: 'TensorFlow', progress: 75 },
  ],
  performanceScore: 82,
};

// AI Insights
export const aiInsights: AIInsight[] = [
  {
    id: 'insight-1',
    type: 'recommendation',
    title: 'Learn Kubernetes for DevOps',
    description: 'Based on your Docker expertise and backend skills, Kubernetes would be a great next step.',
    icon: '🚀',
  },
  {
    id: 'insight-2',
    type: 'achievement',
    title: 'Impressive Streak!',
    description: 'You&apos;ve maintained a 28-day learning streak. Keep it up!',
    icon: '🔥',
  },
  {
    id: 'insight-3',
    type: 'gap_analysis',
    title: 'Cloud Skills Gap',
    description: 'Consider learning AWS or GCP to round out your backend expertise.',
    icon: '☁️',
  },
  {
    id: 'insight-4',
    type: 'career_path',
    title: 'Senior Engineer Path Unlocked',
    description: 'You&apos;re on track for a senior role within 6 months based on your learning velocity.',
    icon: '📈',
  },
];
